### ISSUE TITLE
'Stem module not found' on Windows 10

### ISSUE THREAD

**Issue by SMWLucasO** [sashaptrw/onionfwd#1] opened 2018-08-07 18:52 UTC
Reproducing the issue:
1. Move the files to D harddrive
2.  Execute the bundle bat file
3. Get all the files, now try executing it using "onionfwd.bat 8080:80"

You'll get an error saying it doesn't know whatever the stem module is supposed to be.

**Comment by sashaptrw** [comment] 2018-08-07 19:29
Appears to be an issue caused by using pip in combination with the embedded Python zip.
```
C:\Users\sp\Workspace\onionfwd>python\python.exe -m pip install --no-cache stem
Collecting stem
  Downloading https://files.pythonhosted.org/packages/11/d5/e51983f81b38408ae2f0e166481ad867962f6fa07610fe71119534e12d41/stem-1.6.0.tar.gz (2.0MB)
    100% |████████████████████████████████| 2.1MB 20.5MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sp\AppData\Local\Temp\pip-install-azzy7iat\stem\setup.py", line 34, in <module>
        import stem
    ModuleNotFoundError: No module named 'stem'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\sp\AppData\Local\Temp\pip-install-azzy7iat\stem\

```
 I will try to create a workaround.

**Comment by sashaptrw** [comment] 2018-08-07 20:48
Should be fixed in https://github.com/sashaptrw/onionfwd/commit/872cb7266af978fa5ac61da649b372c459c4666d

**Closed** 2018-08-07 21:25 UTC
Labels: bug, windows-bundle
